title:             Tech Blog
email:             heisenberg.yoon@travelflan.com
description:       A Blog by Heisenberg
author:            Heisenberg
# baseurl:           "localhost:4000/"
baseurl:           "/"
url:               "http://heisenberg1217.github.io"
permalink: /:year/:month/:day/:title/

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
krandown:
  input: GFM
  highlighter: rouge
paginate:          5
paginate_path:     "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

asset_url: /assets